
/**USER MANAGER**/
const USER_MANAGER_HOST = 'xx.xxx.xx.7';
const USER_MANAGER_PORT = 10010;

/**DATA MANAGER**/
const NICE_SERVICE_HOST = 'xx.xxx.xx.10';
const NICE_SERVICE_PORT = 50071;
const HIVE_META_STORE_HOST = 'xx.xxx.xx.10';
const HIVE_META_STORE_PORT = 10000;

/**SECURITY CENTER**/
const SECURITY_CENTER_HOST = 'xx.xxx.xx.7';
const SECURITY_CENTER_PORT = 10010;


//Python
const HIVE_THRIFT_HOST = 'xx.xxx.xx.7';
const HIVE_THRIFT_PORT = '3002';
module.exports = {
    HIVE_THRIFT_HOST,
    HIVE_THRIFT_PORT,
    USER_MANAGER_HOST,
    USER_MANAGER_PORT,
    NICE_SERVICE_HOST,
    NICE_SERVICE_PORT,
    SECURITY_CENTER_HOST,
    SECURITY_CENTER_PORT,
    HIVE_META_STORE_HOST,
    HIVE_META_STORE_PORT
};

